apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: techtrends
  name: techtrends
  namespace: {{.Values.namespace}}
spec:
  replicas: {{.Values.replicaCount}}
  selector:
    matchLabels:
      app: techtrends
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: techtrends
    spec:
      containers:
        - image: {{.Values.image.repository}}: {{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pullPolicy}}
          name: techtrends
          ports:
            - containerPort: {{.Values.containerPort}}
              protocol: TCP
          readinessPort:
            httpGet:
              path: {{.Values.readinessPort.httpGet.path}}
              port: {{.Values.readinessPort.httpGet.port}}
          livenessProbe:
            httpGet:
              path: {{.Values.livenessProbe.httpGet.path}}
              port: {{.Values.livenessProbe.httpGet.port}}
          resources:
            requests:
              cpu: {{.Values.resources.requests.cpu}}
              memory: {{.Values.resources.requests.memory}}
            limits:
              cpu: {{.Values.resources.limits.cpu}}
              memory: {{.Values.resources.limits.memory}}